# Nudge rules for Rust code style enforcement.
#
# These rules demonstrate how to convert common Rust coding guidelines
# into Nudge rule definitions. Copy and adapt for your projects.

version: 1

rules:
  # Catch `use` statements inside function bodies.
  # Pattern: lines starting with horizontal whitespace followed by `use `.
  # Note: This regex has false positives (e.g., `use` inside `mod test`).
  #       For precise AST-based matching, use the SyntaxTree matcher below.
  - name: no-inline-imports
    description: Move imports to the top of the file
    message: Move this `use` statement to the top of the file with other imports, then retry.
    on:
      - hook: PreToolUse
        tool: Write
        file: "**/*.rs"
        content:
          - kind: Regex
            pattern: "(?m)^[ \\t]+use "
      - hook: PreToolUse
        tool: Edit
        file: "**/*.rs"
        new_content:
          - kind: Regex
            pattern: "(?m)^[ \\t]+use "

  # Catch left-hand side type annotations in variable declarations.
  # Pattern: `let name: Type = ...` or `let mut name: Type = ...`
  - name: no-lhs-type-annotations
    description: Use type inference or turbofish instead of LHS annotations
    message: "Remove this type annotation. Use turbofish (`collect::<Vec<_>>()`) or type inference instead, then retry."
    on:
      - hook: PreToolUse
        tool: Write
        file: "**/*.rs"
        content:
          - kind: Regex
            pattern: "(?m)^\\s*let\\s+(mut\\s+)?[a-zA-Z_][a-zA-Z0-9_]*\\s*:\\s*"
      - hook: PreToolUse
        tool: Edit
        file: "**/*.rs"
        new_content:
          - kind: Regex
            pattern: "(?m)^\\s*let\\s+(mut\\s+)?[a-zA-Z_][a-zA-Z0-9_]*\\s*:\\s*"

  # Catch unnecessarily fully qualified paths in code (not imports).
  # Pattern: paths with 2+ `::` separators followed by ::, (, or <
  - name: no-qualified-paths
    description: Simplify qualified paths by adding imports
    message: "Simplify this path by adding a `use` import at file top, then retry. Exception: keep qualified if it improves clarity."
    on:
      - hook: PreToolUse
        tool: Write
        file: "**/*.rs"
        content:
          - kind: Regex
            pattern: "std(::[a-zA-Z_][a-zA-Z0-9_]*){2,}(::|\\(|<)"
      - hook: PreToolUse
        tool: Edit
        file: "**/*.rs"
        new_content:
          - kind: Regex
            pattern: "std(::[a-zA-Z_][a-zA-Z0-9_]*){2,}(::|\\(|<)"

  # Suggest using `pretty_assertions` for better test output.
  - name: prefer-pretty-assertions
    description: Use pretty_assertions in tests for better diff output
    message: "Use `pretty_assert_eq!` instead. Add `use pretty_assertions::assert_eq as pretty_assert_eq;` at file top, then retry."
    on:
      - hook: PreToolUse
        tool: Write
        file: "**/*.rs"
        content:
          - kind: Regex
            pattern: "assert_eq!"
      - hook: PreToolUse
        tool: Edit
        file: "**/*.rs"
        new_content:
          - kind: Regex
            pattern: "assert_eq!"

  # Catch .unwrap() calls and suggest .expect() instead.
  # Demonstrates the suggestion feature with named capture groups.
  - name: no-unwrap
    description: Use .expect() instead of .unwrap() for better error messages
    message: "{{ $suggestion }}"
    on:
      - hook: PreToolUse
        tool: Write
        file: "**/*.rs"
        content:
          - kind: Regex
            pattern: "(?P<expr>[a-zA-Z_][a-zA-Z0-9_]*)\\.unwrap\\(\\)"
            suggestion: 'Replace `{{ $expr }}.unwrap()` with `{{ $expr }}.expect("descriptive error message")`'
      - hook: PreToolUse
        tool: Edit
        file: "**/*.rs"
        new_content:
          - kind: Regex
            pattern: "(?P<expr>[a-zA-Z_][a-zA-Z0-9_]*)\\.unwrap\\(\\)"
            suggestion: 'Replace `{{ $expr }}.unwrap()` with `{{ $expr }}.expect("descriptive error message")`'

  # Redirect docs.rs fetches to local cargo registry.
  # Demonstrates the WebFetch matcher with URL capture groups.
  - name: prefer-local-docs
    description: Read local crate source instead of fetching from docs.rs
    message: "{{ $suggestion }}"
    on:
      - hook: PreToolUse
        tool: WebFetch
        url:
          - kind: Regex
            pattern: "docs\\.rs/(?P<crate>[^/]+)"
            suggestion: "Don't fetch from docs.rs. Instead, read the local source at ~/.cargo/registry/src/*/{{ $crate }}-*"
