# Test rules for Nudge integration tests.
# Keep these rules simple and focused on testing the rule system itself.

version: 1

rules:
  # Rule 1: Catch `use` statements inside function bodies
  # Pattern: lines starting with whitespace followed by `use `
  # (?m) enables multiline mode so ^ matches at line boundaries.
  - name: no-inline-imports
    description: Move imports to the top of the file
    message: Move this `use` statement to the top of the file with other imports.
    on:
      - hook: PreToolUse
        tool: Write
        file: "**/*.rs"
        content:
          - kind: Regex
            pattern: "(?m)^[ \\t]+use "
      - hook: PreToolUse
        tool: Edit
        file: "**/*.rs"
        new_content:
          - kind: Regex
            pattern: "(?m)^[ \\t]+use "

  # Rule 2: Catch LHS type annotations (simplified)
  - name: no-lhs-type-annotations
    description: Use type inference or turbofish instead
    message: Remove LHS type annotations. Use turbofish or type inference instead.
    on:
      - hook: PreToolUse
        tool: Write
        file: "**/*.rs"
        content:
          - kind: Regex
            pattern: "(?m)let\\s+\\w+\\s*:\\s*Vec<"
      - hook: PreToolUse
        tool: Edit
        file: "**/*.rs"
        new_content:
          - kind: Regex
            pattern: "(?m)let\\s+\\w+\\s*:\\s*Vec<"

  # Rule 3: Redirect docs.rs fetches to local cargo registry
  - name: prefer-local-docs
    description: Read local crate source instead of fetching from docs.rs
    message: "{{ $suggestion }}"
    on:
      - hook: PreToolUse
        tool: WebFetch
        url:
          - kind: Regex
            pattern: "docs\\.rs/(?P<crate>[^/]+)"
            suggestion: "Don't fetch from docs.rs. Instead, read the local source at ~/.cargo/registry/src/*/{{ $crate }}-*"
